name: release

on:
  push:
    branches:
      - "develop"
      - "BRANCH2"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

# https://github.com/marketplace/actions/skip-based-on-commit-message
jobs:
  develop:
    if: |
          github.ref == 'refs/heads/develop' 
            && contains(github.event.head_commit.message, '--BUILD')
# https://github.com/orgs/community/discussions/25641
    name: Build and test STG
    runs-on: ubuntu-latest
# https://stackoverflow.com/questions/71361539/github-action-test-if-a-commit-containing-a-specific-word-was-previously-made
# https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event
    steps:
      - name: Trigger build in another repository
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TRIDZ_TOKEN }}" \
            https://api.github.com/repos/tridz-dev/visaguy_gitops/actions/workflows/release_on_dispatch_stg.yml/dispatches \
            -d '{"ref":"main"}'

  BRANCH2:
    if: |
          github.ref == 'refs/heads/BRANCH2' 
            && contains(github.event.head_commit.message, '--BUILD')
    name: Build and test
    runs-on: ubuntu-latest
# https://stackoverflow.com/questions/71361539/github-action-test-if-a-commit-containing-a-specific-word-was-previously-made
# https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event
    steps:
      - name: Trigger build in another repository
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.TRIDZ_TOKEN }}" \
            https://api.github.com/repos/OWNER/REPO/actions/workflows/WORKFLOW.yml/dispatches \
            -d '{"ref":"main"}'